from wgl4 import (
    WGL4, WGL4_PRINTING
)
from cp437 import (
    CODE_PAGE_437, CODE_PAGE_437_SUPPLEMENT, CODE_PAGE_437_ALL,
    CODE_PAGE_437_PRINTING, CODE_PAGE_437_SUPPLEMENT_PRINTING, CODE_PAGE_437_ALL_PRINTING
)
from aglfn import (
    AGLFN, AGLFN_PRINTING
)

GLYPH_LIST = list(set(WGL4 + CODE_PAGE_437_SUPPLEMENT + AGLFN))
GLYPH_LIST_PRINTING = list(set(WGL4_PRINTING + CODE_PAGE_437_SUPPLEMENT_PRINTING + AGLFN_PRINTING))

GLYPH_LIST.sort()
GLYPH_LIST_PRINTING.sort()
