PANOSE_FAMILY_KIND = [
    "Any",
    "No Fit",
    "Latin Text",
    "Latin Hand Written",
    "Latin Decoratives",
    "Latin Symbol",
]
PANOSE_LATIN_TEXT = [
    "Family Kind",
    "Serif Style",
    "Weight",
    "Proportion",
    "Contrast",
    "Stroke Variation",
    "Arm Style",
    "Letterform",
    "Midline",
    "X-height",
]
PANOSE_LATIN_HAND_WRITTEN = [
    "Family Kind",
    "Tool Kind",
    "Weight",
    "Spacing",
    "Aspect Ratio",
    "Contrast",
    "Topology",
    "Form",
    "Finials",
    "X-ascent",
]
PANOSE_LATIN_DECORATIVES = [
    "Family Kind",
    "Class",
    "Weight",
    "Aspect",
    "Contrast",
    "Serif Variant",
    "Treatment",
    "Lining",
    "Topology",
    "Range of Characters",
]
PANOSE_LATIN_SYMBOL = [
    "Family Kind",
    "Kind",
    "Weight",
    "Spacing",
    "Aspect Ratio & Contrast",
    "Aspect Ratio of Character 94",
    "Aspect Ratio of Character 119",
    "Aspect Ratio of Character 157",
    "Aspect Ratio of Character 163",
    "Aspect Ratio of Character 211",
]
PANOSE_1_SERIF_STYLE = [
    "Any",
    "No Fit",
    "Cove",
    "Obtuse Cove",
    "Square Cove",
    "Obtuse Square Cove",
    "Square",
    "Thin",
    "Oval",
    "Exaggerated",
    "Triangle",
    "Normal Sans",
    "Obtuse Sans",
    "Perpendicular Sans",
    "Flared",
    "Rounded",
]
PANOSE_1_WEIGHT = [
    "Any",
    "No Fit",
    "Very Light",
    "Light",
    "Thin",
    "Book",
    "Medium",
    "Demi",
    "Bold",
    "Heavy",
    "Black",
    "Extra Black",
]
PANOSE_1_PROPORTION = [
    "Any",
    "No fit",
    "Old Style",
    "Modern",
    "Even Width",
    "Extended",
    "Condensed",
    "Very Extended",
    "Very Condensed",
    "Monospaced",
]
PANOSE_1_CONTRAST = [
    "Any",
    "No Fit",
    "None",
    "Very Low",
    "Low",
    "Medium Low",
    "Medium",
    "Medium High",
    "High",
    "Very High",
]
PANOSE_1_STROKE_VARIATION = [
    "Any",
    "No Fit",
    "No Variation",
    "Gradual/Diagonal",
    "Gradual/Transitional",
    "Gradual/Vertical",
    "Gradual/Horizontal",
    "Rapid/Vertical",
    "Rapid/Horizontal",
    "Instant/Vertical",
    "Instant/Horizontal",
]
PANOSE_1_ARM_STYLE = [
    "Any",
    "No Fit",
    "Straight Arms/Horizontal",
    "Straight Arms/Wedge",
    "Straight Arms/Vertical",
    "Straight Arms/Single Serif",
    "Straight Arms/Double Serif",
    "Non-Straight/Horizontal",
    "Non-Straight/Wedge",
    "Non-Straight/Vertical",
    "Non-Straight/Single Serif",
    "Non-Straight/Double Serif",
]
PANOSE_1_LETTERFORM = [
    "Any",
    "No Fit",
    "Normal/Contact",
    "Normal/Weighted",
    "Normal/Boxed",
    "Normal/Flattened",
    "Normal/Rounded",
    "Normal/Off Center",
    "Normal/Square",
    "Oblique/Contact",
    "Oblique/Weighted",
    "Oblique/Boxed",
    "Oblique/Flattened",
    "Oblique/Rounded",
    "Oblique/Off Center",
    "Oblique/Square",
]
PANOSE_1_MIDLINE = [
    "Any",
    "No Fit",
    "Standard/Trimmed",
    "Standard/Pointed",
    "Standard/Serifed",
    "High/Trimmed",
    "High/Pointed",
    "High/Serifed",
    "Constant/Trimmed",
    "Constant/Pointed",
    "Constant/Serifed",
    "Low/Trimmed",
    "Low/Pointed",
    "Low/Serifed",
]
PANOSE_1_X_HEIGHT = [
    "Any",
    "No Fit",
    "Constant/Small",
    "Constant/Standard",
    "Constant/Large",
    "Ducking/Small",
    "Ducking/Standard",
    "Ducking/Large",
]
PANOSE_2_TOOL_KIND = [
    "Any",
    "No Fit",
    "Flat Nib",
    "Pressure Point",
    "Engraved",
    "Ball (Round Cap)",
    "Brush",
    "Rough",
    "Felt Pen/Brush Tip",
    "Wild Brush - Drips a lot",
]
PANOSE_2_WEIGHT = [
    "Any",
    "No Fit",
    "Very Light",
    "Light",
    "Thin",
    "Book",
    "Medium",
    "Demi",
    "Bold",
    "Heavy",
    "Black",
    "Extra Black",
]
PANOSE_2_SPACING = [
    "Any",
    "No fit",
    "Proportional Spaced",
    "Monospaced",
]
PANOSE_2_ASPECT_RATIO = [
    "Any",
    "No Fit",
    "Very Condensed",
    "Condensed",
    "Normal",
    "Expanded",
    "Very Expanded",
]
PANOSE_2_CONTRAST = [
    "Any",
    "No Fit",
    "None",
    "Very Low",
    "Low",
    "Medium Low",
    "Medium",
    "Medium High",
    "High",
    "Very High",
]
PANOSE_2_TOPOLOGY = [
    "Any",
    "No Fit",
    "Roman Disconnected",
    "Roman Trailing",
    "Roman Connected",
    "Cursive Disconnected",
    "Cursive Trailing",
    "Cursive Connected",
    "Blackletter Disconnected",
    "Blackletter Trailing",
    "Blackletter Connected",
]
PANOSE_2_FORM = [
    "Any",
    "No Fit",
    "Upright / No Wrapping",
    "Upright / Some Wrapping",
    "Upright / More Wrapping",
    "Upright / Extreme Wrapping",
    "Oblique / No Wrapping",
    "Oblique / Some Wrapping",
    "Oblique / More Wrapping",
    "Oblique / Extreme Wrapping",
    "Exaggerated / No Wrapping",
    "Exaggerated / Some Wrapping",
    "Exaggerated / More Wrapping",
    "Exaggerated / Extreme Wrapping",
]
PANOSE_2_FINIALS = [
    "Any",
    "No Fit",
    "None / No loops",
    "None / Closed loops",
    "None / Open loops",
    "Sharp / No loops",
    "Sharp / Closed loops",
    "Sharp / Open loops",
    "Tapered / No loops",
    "Tapered / Closed loops",
    "Tapered / Open loops",
    "Round / No loops",
    "Round / Closed loops",
    "Round / Open loops",
]
PANOSE_2_X_ASCENT = [
    "Any",
    "No Fit",
    "Very Low",
    "Low",
    "Medium",
    "High",
    "Very High",
]
PANOSE_3_CLASS = [
    "Any",
    "No Fit",
    "Derivative",
    "Non-standard Topology",
    "Non-standard Elements",
    "Non-standard Aspect",
    "Initials",
    "Cartoon",
    "Picture Stems",
    "Ornamented",
    "Text and Background",
    "Collage",
    "Montage",
]
PANOSE_3_WEIGHT = [
    "Any",
    "No Fit",
    "Very Light",
    "Light",
    "Thin",
    "Book",
    "Medium",
    "Demi",
    "Bold",
    "Heavy",
    "Black",
    "Extra Black",
]
PANOSE_3_ASPECT = [
    "Any",
    "No fit",
    "Super Condensed",
    "Very Condensed",
    "Condensed",
    "Normal",
    "Extended",
    "Very Extended",
    "Super Extended",
    "Monospaced",
]
PANOSE_3_CONTRAST = [
    "Any",
    "No Fit",
    "None",
    "Very Low",
    "Low",
    "Medium Low",
    "Medium",
    "Medium High",
    "High",
    "Very High",
    "Horizontal Low",
    "Horizontal Medium",
    "Horizontal High",
    "Broken",
]
PANOSE_3_SERIF_VARIANT = [
    "Any",
    "No Fit",
    "Cove",
    "Obtuse Cove",
    "Square Cove",
    "Obtuse Square Cove",
    "Square",
    "Thin",
    "Oval",
    "Exaggerated",
    "Triangle",
    "Normal Sans",
    "Obtuse Sans",
    "Perpendicular Sans",
    "Flared",
    "Rounded",
    "Script",
]
PANOSE_3_TREATMENT = [
    "Any",
    "No Fit",
    "None - Standard Solid Fill",
    "White / No Fill",
    "Patterned Fill",
    "Complex Fill",
    "Shaped Fill",
    "Drawn / Distressed",
]
PANOSE_3_LINING = [
    "Any",
    "No Fit",
    "None",
    "Inline",
    "Outline",
    "Engraved (Multiple Lines)",
    "Shadow",
    "Relief",
    "Backdrop",
]
PANOSE_3_TOPOLOGY = [
    "Any",
    "No Fit",
    "Standard",
    "Square",
    "Multiple Segment",
    "Deco (E,M,S) Waco midlines",
    "Uneven Weighting",
    "Diverse Arms",
    "Diverse Forms",
    "Lombardic Forms",
    "Upper Case in Lower Case",
    "Implied Topology",
    "Horseshoe E and A",
    "Cursive",
    "Blackletter",
    "Swash Variance",
]
PANOSE_3_RANGE_OF_CHARACTERS = [
    "Any",
    "No Fit",
    "Extended Collection",
    "Literals",
    "No Lower Case",
    "Small Caps",
]
PANOSE_4_KIND = [
    "Any",
    "No Fit",
    "Montages",
    "Pictures",
    "Shapes",
    "Scientific",
    "Music",
    "Expert",
    "Patterns",
    "Boarders",
    "Icons",
    "Logos",
    "Industry specific",
]
PANOSE_4_WEIGHT = [
    None,
    "No Fit",
]
PANOSE_4_SPACING = [
    "Any",
    "No fit",
    "Proportional Spaced",
    "Monospaced",
]
PANOSE_4_ASPECT_RATIO_AND_CONTRAST = [
    None,
    "No Fit",
]
PANOSE_4_ASPECT_RATIO_OF_CHARACTER_94 = [
    "Any",
    "No Fit",
    "No Width",
    "Exceptionally Wide",
    "Super Wide",
    "Very Wide",
    "Wide",
    "Normal",
    "Narrow",
    "Very Narrow",
]
PANOSE_4_ASPECT_RATIO_OF_CHARACTER_119 = [
    "Any",
    "No Fit",
    "No Width",
    "Exceptionally Wide",
    "Super Wide",
    "Very Wide",
    "Wide",
    "Normal",
    "Narrow",
    "Very Narrow",
]
PANOSE_4_ASPECT_RATIO_OF_CHARACTER_157 = [
    "Any",
    "No Fit",
    "No Width",
    "Exceptionally Wide",
    "Super Wide",
    "Very Wide",
    "Wide",
    "Normal",
    "Narrow",
    "Very Narrow",
]
PANOSE_4_ASPECT_RATIO_OF_CHARACTER_163 = [
    "Any",
    "No Fit",
    "No Width",
    "Exceptionally Wide",
    "Super Wide",
    "Very Wide",
    "Wide",
    "Normal",
    "Narrow",
    "Very Narrow",
]
PANOSE_4_ASPECT_RATIO_OF_CHARACTER_211 = [
    "Any",
    "No Fit",
    "No Width",
    "Exceptionally Wide",
    "Super Wide",
    "Very Wide",
    "Wide",
    "Normal",
    "Narrow",
    "Very Narrow",
]
# 1 would be panose(0)
# 3 would be panose(5)
# PANOSE_NAME[1][5] => "Stroke Variation"
# PANOSE_VALUE[1][5][3] => "Gradual/Diagonal"
PANOSE_NAME = [
    None,
    None,
    PANOSE_LATIN_TEXT,
    PANOSE_LATIN_HAND_WRITTEN,
    PANOSE_LATIN_DECORATIVES,
    PANOSE_LATIN_SYMBOL,
]
PANOSE_VALUE = [
    [
        PANOSE_FAMILY_KIND,
        PANOSE_1_SERIF_STYLE,
        PANOSE_1_WEIGHT,
        PANOSE_1_PROPORTION,
        PANOSE_1_CONTRAST,
        PANOSE_1_STROKE_VARIATION,
        PANOSE_1_ARM_STYLE,
        PANOSE_1_LETTERFORM,
        PANOSE_1_MIDLINE,
        PANOSE_1_X_HEIGHT,
    ],
    [
        PANOSE_FAMILY_KIND,
        PANOSE_2_TOOL_KIND,
        PANOSE_2_WEIGHT,
        PANOSE_2_SPACING,
        PANOSE_2_ASPECT_RATIO,
        PANOSE_2_CONTRAST,
        PANOSE_2_TOPOLOGY,
        PANOSE_2_FORM,
        PANOSE_2_FINIALS,
        PANOSE_2_X_ASCENT,
    ],
    [
        PANOSE_FAMILY_KIND,
        PANOSE_3_CLASS,
        PANOSE_3_WEIGHT,
        PANOSE_3_ASPECT,
        PANOSE_3_CONTRAST,
        PANOSE_3_SERIF_VARIANT,
        PANOSE_3_TREATMENT,
        PANOSE_3_LINING,
        PANOSE_3_TOPOLOGY,
        PANOSE_3_RANGE_OF_CHARACTERS,
    ],
    [
        PANOSE_FAMILY_KIND,
        PANOSE_4_KIND,
        PANOSE_4_WEIGHT,
        PANOSE_4_SPACING,
        PANOSE_4_ASPECT_RATIO_AND_CONTRAST,
        PANOSE_4_ASPECT_RATIO_OF_CHARACTER_94,
        PANOSE_4_ASPECT_RATIO_OF_CHARACTER_119,
        PANOSE_4_ASPECT_RATIO_OF_CHARACTER_157,
        PANOSE_4_ASPECT_RATIO_OF_CHARACTER_163,
        PANOSE_4_ASPECT_RATIO_OF_CHARACTER_211,
    ],
]
