class WGL4:
    pass

# Source: https://docs.microsoft.com/en-us/typography/opentype/spec/wgl4
WGL4.codepoints = [
    0x0020,                     # SPACE
    0x0021,                     # EXCLAMATION MARK
    0x0022,                     # QUOTATION MARK
    0x0023,                     # NUMBER SIGN
    0x0024,                     # DOLLAR SIGN
    0x0025,                     # PERCENT SIGN
    0x0026,                     # AMPERSAND
    0x0027,                     # APOSTROPHE (APOSTROPHE-QUOTE)
    0x0028,                     # LEFT PARENTHESIS (OPENING PARENTHESIS)
    0x0029,                     # RIGHT PARENTHESIS (CLOSING PARENTHESIS)
    0x002a,                     # ASTERISK
    0x002b,                     # PLUS SIGN
    0x002c,                     # COMMA
    0x002d,                     # HYPHEN-MINUS
    0x002e,                     # FULL STOP (PERIOD)
    0x002f,                     # SOLIDUS (SLASH)
    0x0030,                     # DIGIT ZERO
    0x0031,                     # DIGIT ONE
    0x0032,                     # DIGIT TWO
    0x0033,                     # DIGIT THREE
    0x0034,                     # DIGIT FOUR
    0x0035,                     # DIGIT FIVE
    0x0036,                     # DIGIT SIX
    0x0037,                     # DIGIT SEVEN
    0x0038,                     # DIGIT EIGHT
    0x0039,                     # DIGIT NINE
    0x003a,                     # COLON
    0x003b,                     # SEMICOLON
    0x003c,                     # LESS-THAN SIGN
    0x003d,                     # EQUALS SIGN
    0x003e,                     # GREATER-THAN SIGN
    0x003f,                     # QUESTION MARK
    0x0040,                     # COMMERCIAL AT
    0x0041,                     # LATIN CAPITAL LETTER A
    0x0042,                     # LATIN CAPITAL LETTER B
    0x0043,                     # LATIN CAPITAL LETTER C
    0x0044,                     # LATIN CAPITAL LETTER D
    0x0045,                     # LATIN CAPITAL LETTER E
    0x0046,                     # LATIN CAPITAL LETTER F
    0x0047,                     # LATIN CAPITAL LETTER G
    0x0048,                     # LATIN CAPITAL LETTER H
    0x0049,                     # LATIN CAPITAL LETTER I
    0x004a,                     # LATIN CAPITAL LETTER J
    0x004b,                     # LATIN CAPITAL LETTER K
    0x004c,                     # LATIN CAPITAL LETTER L
    0x004d,                     # LATIN CAPITAL LETTER M
    0x004e,                     # LATIN CAPITAL LETTER N
    0x004f,                     # LATIN CAPITAL LETTER O
    0x0050,                     # LATIN CAPITAL LETTER P
    0x0051,                     # LATIN CAPITAL LETTER Q
    0x0052,                     # LATIN CAPITAL LETTER R
    0x0053,                     # LATIN CAPITAL LETTER S
    0x0054,                     # LATIN CAPITAL LETTER T
    0x0055,                     # LATIN CAPITAL LETTER U
    0x0056,                     # LATIN CAPITAL LETTER V
    0x0057,                     # LATIN CAPITAL LETTER W
    0x0058,                     # LATIN CAPITAL LETTER X
    0x0059,                     # LATIN CAPITAL LETTER Y
    0x005a,                     # LATIN CAPITAL LETTER Z
    0x005b,                     # LEFT SQUARE BRACKET (OPENING SQUARE BRACKET)
    0x005c,                     # REVERSE SOLIDUS (BACKSLASH)
    0x005d,                     # RIGHT SQUARE BRACKET (CLOSING SQUARE BRACKET)
    0x005e,                     # CIRCUMFLEX ACCENT (SPACING CIRCUMFLEX)
    0x005f,                     # LOW LINE (SPACING UNDERSCORE)
    0x0060,                     # GRAVE ACCENT (SPACING GRAVE)
    0x0061,                     # LATIN SMALL LETTER A
    0x0062,                     # LATIN SMALL LETTER B
    0x0063,                     # LATIN SMALL LETTER C
    0x0064,                     # LATIN SMALL LETTER D
    0x0065,                     # LATIN SMALL LETTER E
    0x0066,                     # LATIN SMALL LETTER F
    0x0067,                     # LATIN SMALL LETTER G
    0x0068,                     # LATIN SMALL LETTER H
    0x0069,                     # LATIN SMALL LETTER I
    0x006a,                     # LATIN SMALL LETTER J
    0x006b,                     # LATIN SMALL LETTER K
    0x006c,                     # LATIN SMALL LETTER L
    0x006d,                     # LATIN SMALL LETTER M
    0x006e,                     # LATIN SMALL LETTER N
    0x006f,                     # LATIN SMALL LETTER O
    0x0070,                     # LATIN SMALL LETTER P
    0x0071,                     # LATIN SMALL LETTER Q
    0x0072,                     # LATIN SMALL LETTER R
    0x0073,                     # LATIN SMALL LETTER S
    0x0074,                     # LATIN SMALL LETTER T
    0x0075,                     # LATIN SMALL LETTER U
    0x0076,                     # LATIN SMALL LETTER V
    0x0077,                     # LATIN SMALL LETTER W
    0x0078,                     # LATIN SMALL LETTER X
    0x0079,                     # LATIN SMALL LETTER Y
    0x007a,                     # LATIN SMALL LETTER Z
    0x007b,                     # LEFT CURLY BRACKET (OPENING CURLY BRACKET)
    0x007c,                     # VERTICAL LINE (VERTICAL BAR)
    0x007d,                     # RIGHT CURLY BRACKET (CLOSING CURLY BRACKET)
    0x007e,                     # TILDE
    0x00a0,                     # NO-BREAK SPACE (NON-BREAKING SPACE)
    0x00a1,                     # INVERTED EXCLAMATION MARK
    0x00a2,                     # CENT SIGN
    0x00a3,                     # POUND SIGN
    0x00a4,                     # CURRENCY SIGN
    0x00a5,                     # YEN SIGN
    0x00a6,                     # BROKEN BAR (BROKEN VERTICAL BAR)
    0x00a7,                     # SECTION SIGN
    0x00a8,                     # DIAERESIS (SPACING DIAERESIS)
    0x00a9,                     # COPYRIGHT SIGN
    0x00aa,                     # FEMININE ORDINAL INDICATOR
    0x00ab,                     # LEFT-POINTING DOUBLE ANGLE QUOTATION MARK (LEFT POINTING GUILLEMET)
    0x00ac,                     # NOT SIGN
    0x00ad,                     # SOFT HYPHEN
    0x00ae,                     # REGISTERED SIGN (REGISTERED TRADE MARK SIGN)
    0x00af,                     # MACRON (SPACING MACRON)
    0x00b0,                     # DEGREE SIGN
    0x00b1,                     # PLUS-MINUS SIGN (PLUS-OR-MINUS SIGN)
    0x00b2,                     # SUPERSCRIPT TWO (SUPERSCRIPT DIGIT TWO)
    0x00b3,                     # SUPERSCRIPT THREE (SUPERSCRIPT DIGIT THREE)
    0x00b4,                     # ACUTE ACCENT (SPACING ACUTE)
    0x00b5,                     # MICRO SIGN
    0x00b6,                     # PILCROW SIGN (PARAGRAPH SIGN)
    0x00b7,                     # MIDDLE DOT
    0x00b8,                     # CEDILLA (SPACING CEDILLA)
    0x00b9,                     # SUPERSCRIPT ONE (SUPERSCRIPT DIGIT ONE)
    0x00ba,                     # MASCULINE ORDINAL INDICATOR
    0x00bb,                     # RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK (RIGHT POINTING GUILLEMET)
    0x00bc,                     # VULGAR FRACTION ONE QUARTER (FRACTION ONE QUARTER)
    0x00bd,                     # VULGAR FRACTION ONE HALF (FRACTION ONE HALF)
    0x00be,                     # VULGAR FRACTION THREE QUARTERS (FRACTION THREE QUARTERS)
    0x00bf,                     # INVERTED QUESTION MARK
    0x00c0,                     # LATIN CAPITAL LETTER A WITH GRAVE (LATIN CAPITAL LETTER A GRAVE)
    0x00c1,                     # LATIN CAPITAL LETTER A WITH ACUTE (LATIN CAPITAL LETTER A ACUTE)
    0x00c2,                     # LATIN CAPITAL LETTER A WITH CIRCUMFLEX (LATIN CAPITAL LETTER A CIRCUMFLEX)
    0x00c3,                     # LATIN CAPITAL LETTER A WITH TILDE (LATIN CAPITAL LETTER A TILDE)
    0x00c4,                     # LATIN CAPITAL LETTER A WITH DIAERESIS (LATIN CAPITAL LETTER A DIAERESIS)
    0x00c5,                     # LATIN CAPITAL LETTER A WITH RING ABOVE (LATIN CAPITAL LETTER A RING)
    0x00c6,                     # LATIN CAPITAL LETTER AE (LATIN CAPITAL LETTER A E)
    0x00c7,                     # LATIN CAPITAL LETTER C WITH CEDILLA (LATIN CAPITAL LETTER C CEDILLA)
    0x00c8,                     # LATIN CAPITAL LETTER E WITH GRAVE (LATIN CAPITAL LETTER E GRAVE)
    0x00c9,                     # LATIN CAPITAL LETTER E WITH ACUTE (LATIN CAPITAL LETTER E ACUTE)
    0x00ca,                     # LATIN CAPITAL LETTER E WITH CIRCUMFLEX (LATIN CAPITAL LETTER E CIRCUMFLEX)
    0x00cb,                     # LATIN CAPITAL LETTER E WITH DIAERESIS (LATIN CAPITAL LETTER E DIAERESIS)
    0x00cc,                     # LATIN CAPITAL LETTER I WITH GRAVE (LATIN CAPITAL LETTER I GRAVE)
    0x00cd,                     # LATIN CAPITAL LETTER I WITH ACUTE (LATIN CAPITAL LETTER I ACUTE)
    0x00ce,                     # LATIN CAPITAL LETTER I WITH CIRCUMFLEX (LATIN CAPITAL LETTER I CIRCUMFLEX)
    0x00cf,                     # LATIN CAPITAL LETTER I WITH DIAERESIS (LATIN CAPITAL LETTER I DIAERESIS)
    0x00d0,                     # LATIN CAPITAL LETTER ETH
    0x00d1,                     # LATIN CAPITAL LETTER N WITH TILDE (LATIN CAPITAL LETTER N TILDE)
    0x00d2,                     # LATIN CAPITAL LETTER O WITH GRAVE (LATIN CAPITAL LETTER O GRAVE)
    0x00d3,                     # LATIN CAPITAL LETTER O WITH ACUTE (LATIN CAPITAL LETTER O ACUTE)
    0x00d4,                     # LATIN CAPITAL LETTER O WITH CIRCUMFLEX (LATIN CAPITAL LETTER O CIRCUMFLEX)
    0x00d5,                     # LATIN CAPITAL LETTER O WITH TILDE (LATIN CAPITAL LETTER O TILDE)
    0x00d6,                     # LATIN CAPITAL LETTER O WITH DIAERESIS (LATIN CAPITAL LETTER O DIAERESIS)
    0x00d7,                     # MULTIPLICATION SIGN
    0x00d8,                     # LATIN CAPITAL LETTER O WITH STROKE (LATIN CAPITAL LETTER O SLASH)
    0x00d9,                     # LATIN CAPITAL LETTER U WITH GRAVE (LATIN CAPITAL LETTER U GRAVE)
    0x00da,                     # LATIN CAPITAL LETTER U WITH ACUTE (LATIN CAPITAL LETTER U ACUTE)
    0x00db,                     # LATIN CAPITAL LETTER U WITH CIRCUMFLEX (LATIN CAPITAL LETTER U CIRCUMFLEX)
    0x00dc,                     # LATIN CAPITAL LETTER U WITH DIAERESIS (LATIN CAPITAL LETTER U DIAERESIS)
    0x00dd,                     # LATIN CAPITAL LETTER Y WITH ACUTE (LATIN CAPITAL LETTER Y ACUTE)
    0x00de,                     # LATIN CAPITAL LETTER THORN
    0x00df,                     # LATIN SMALL LETTER SHARP S
    0x00e0,                     # LATIN SMALL LETTER A WITH GRAVE (LATIN SMALL LETTER A GRAVE)
    0x00e1,                     # LATIN SMALL LETTER A WITH ACUTE (LATIN SMALL LETTER A ACUTE)
    0x00e2,                     # LATIN SMALL LETTER A WITH CIRCUMFLEX (LATIN SMALL LETTER A CIRCUMFLEX)
    0x00e3,                     # LATIN SMALL LETTER A WITH TILDE (LATIN SMALL LETTER A TILDE)
    0x00e4,                     # LATIN SMALL LETTER A WITH DIAERESIS (LATIN SMALL LETTER A DIAERESIS)
    0x00e5,                     # LATIN SMALL LETTER A WITH RING ABOVE (LATIN SMALL LETTER A RING)
    0x00e6,                     # LATIN SMALL LETTER AE (LATIN SMALL LETTER A E)
    0x00e7,                     # LATIN SMALL LETTER C WITH CEDILLA (LATIN SMALL LETTER C CEDILLA)
    0x00e8,                     # LATIN SMALL LETTER E WITH GRAVE (LATIN SMALL LETTER E GRAVE)
    0x00e9,                     # LATIN SMALL LETTER E WITH ACUTE (LATIN SMALL LETTER E ACUTE)
    0x00ea,                     # LATIN SMALL LETTER E WITH CIRCUMFLEX (LATIN SMALL LETTER E CIRCUMFLEX)
    0x00eb,                     # LATIN SMALL LETTER E WITH DIAERESIS (LATIN SMALL LETTER E DIAERESIS)
    0x00ec,                     # LATIN SMALL LETTER I WITH GRAVE (LATIN SMALL LETTER I GRAVE)
    0x00ed,                     # LATIN SMALL LETTER I WITH ACUTE (LATIN SMALL LETTER I ACUTE)
    0x00ee,                     # LATIN SMALL LETTER I WITH CIRCUMFLEX (LATIN SMALL LETTER I CIRCUMFLEX)
    0x00ef,                     # LATIN SMALL LETTER I WITH DIAERESIS (LATIN SMALL LETTER I DIAERESIS)
    0x00f0,                     # LATIN SMALL LETTER ETH
    0x00f1,                     # LATIN SMALL LETTER N WITH TILDE (LATIN SMALL LETTER N TILDE)
    0x00f2,                     # LATIN SMALL LETTER O WITH GRAVE (LATIN SMALL LETTER O GRAVE)
    0x00f3,                     # LATIN SMALL LETTER O WITH ACUTE (LATIN SMALL LETTER O ACUTE)
    0x00f4,                     # LATIN SMALL LETTER O WITH CIRCUMFLEX (LATIN SMALL LETTER O CIRCUMFLEX)
    0x00f5,                     # LATIN SMALL LETTER O WITH TILDE (LATIN SMALL LETTER O TILDE)
    0x00f6,                     # LATIN SMALL LETTER O WITH DIAERESIS (LATIN SMALL LETTER O DIAERESIS)
    0x00f7,                     # DIVISION SIGN
    0x00f8,                     # LATIN SMALL LETTER O WITH STROKE (LATIN SMALL LETTER O SLASH)
    0x00f9,                     # LATIN SMALL LETTER U WITH GRAVE (LATIN SMALL LETTER U GRAVE)
    0x00fa,                     # LATIN SMALL LETTER U WITH ACUTE (LATIN SMALL LETTER U ACUTE)
    0x00fb,                     # LATIN SMALL LETTER U WITH CIRCUMFLEX (LATIN SMALL LETTER U CIRCUMFLEX)
    0x00fc,                     # LATIN SMALL LETTER U WITH DIAERESIS (LATIN SMALL LETTER U DIAERESIS)
    0x00fd,                     # LATIN SMALL LETTER Y WITH ACUTE (LATIN SMALL LETTER Y ACUTE)
    0x00fe,                     # LATIN SMALL LETTER THORN
    0x00ff,                     # LATIN SMALL LETTER Y WITH DIAERESIS (LATIN SMALL LETTER Y DIAERESIS)
    0x0100,                     # LATIN CAPITAL LETTER A WITH MACRON (LATIN CAPITAL LETTER A MACRON)
    0x0101,                     # LATIN SMALL LETTER A WITH MACRON (LATIN SMALL LETTER A MACRON)
    0x0102,                     # LATIN CAPITAL LETTER A WITH BREVE (LATIN CAPITAL LETTER A BREVE)
    0x0103,                     # LATIN SMALL LETTER A WITH BREVE (LATIN SMALL LETTER A BREVE)
    0x0104,                     # LATIN CAPITAL LETTER A WITH OGONEK (LATIN CAPITAL LETTER A OGONEK)
    0x0105,                     # LATIN SMALL LETTER A WITH OGONEK (LATIN SMALL LETTER A OGONEK)
    0x0106,                     # LATIN CAPITAL LETTER C WITH ACUTE (LATIN CAPITAL LETTER C ACUTE)
    0x0107,                     # LATIN SMALL LETTER C WITH ACUTE (LATIN SMALL LETTER C ACUTE)
    0x0108,                     # LATIN CAPITAL LETTER C WITH CIRCUMFLEX (LATIN CAPITAL LETTER C CIRCUMFLEX)
    0x0109,                     # LATIN SMALL LETTER C WITH CIRCUMFLEX (LATIN SMALL LETTER C CIRCUMFLEX)
    0x010a,                     # LATIN CAPITAL LETTER C WITH DOT ABOVE (LATIN CAPITAL LETTER C DOT)
    0x010b,                     # LATIN SMALL LETTER C WITH DOT ABOVE (LATIN SMALL LETTER C DOT)
    0x010c,                     # LATIN CAPITAL LETTER C WITH CARON (LATIN CAPITAL LETTER C HACEK)
    0x010d,                     # LATIN SMALL LETTER C WITH CARON (LATIN SMALL LETTER C HACEK)
    0x010e,                     # LATIN CAPITAL LETTER D WITH CARON (LATIN CAPITAL LETTER D HACEK)
    0x010f,                     # LATIN SMALL LETTER D WITH CARON (LATIN SMALL LETTER D HACEK)
    0x0110,                     # LATIN CAPITAL LETTER D WITH STROKE (LATIN CAPITAL LETTER D BAR)
    0x0111,                     # LATIN SMALL LETTER D WITH STROKE (LATIN SMALL LETTER D BAR)
    0x0112,                     # LATIN CAPITAL LETTER E WITH MACRON (LATIN CAPITAL LETTER E MACRON)
    0x0113,                     # LATIN SMALL LETTER E WITH MACRON (LATIN SMALL LETTER E MACRON)
    0x0114,                     # LATIN CAPITAL LETTER E WITH BREVE (LATIN CAPITAL LETTER E BREVE)
    0x0115,                     # LATIN SMALL LETTER E WITH BREVE (LATIN SMALL LETTER E BREVE)
    0x0116,                     # LATIN CAPITAL LETTER E WITH DOT ABOVE (LATIN CAPITAL LETTER E DOT)
    0x0117,                     # LATIN SMALL LETTER E WITH DOT ABOVE (LATIN SMALL LETTER E DOT)
    0x0118,                     # LATIN CAPITAL LETTER E WITH OGONEK (LATIN CAPITAL LETTER E OGONEK)
    0x0119,                     # LATIN SMALL LETTER E WITH OGONEK (LATIN SMALL LETTER E OGONEK)
    0x011a,                     # LATIN CAPITAL LETTER E WITH CARON (LATIN CAPITAL LETTER E HACEK)
    0x011b,                     # LATIN SMALL LETTER E WITH CARON (LATIN SMALL LETTER E HACEK)
    0x011c,                     # LATIN CAPITAL LETTER G WITH CIRCUMFLEX (LATIN CAPITAL LETTER G CIRCUMFLEX)
    0x011d,                     # LATIN SMALL LETTER G WITH CIRCUMFLEX (LATIN SMALL LETTER G CIRCUMFLEX)
    0x011e,                     # LATIN CAPITAL LETTER G WITH BREVE (LATIN CAPITAL LETTER G BREVE)
    0x011f,                     # LATIN SMALL LETTER G WITH BREVE (LATIN SMALL LETTER G BREVE)
    0x0120,                     # LATIN CAPITAL LETTER G WITH DOT ABOVE (LATIN CAPITAL LETTER G DOT)
    0x0121,                     # LATIN SMALL LETTER G WITH DOT ABOVE (LATIN SMALL LETTER G DOT)
    0x0122,                     # LATIN CAPITAL LETTER G WITH CEDILLA (LATIN CAPITAL LETTER G CEDILLA)
    0x0123,                     # LATIN SMALL LETTER G WITH CEDILLA (LATIN SMALL LETTER G CEDILLA)
    0x0124,                     # LATIN CAPITAL LETTER H WITH CIRCUMFLEX (LATIN CAPITAL LETTER H CIRCUMFLEX)
    0x0125,                     # LATIN SMALL LETTER H WITH CIRCUMFLEX (LATIN SMALL LETTER H CIRCUMFLEX)
    0x0126,                     # LATIN CAPITAL LETTER H WITH STROKE (LATIN CAPITAL LETTER H BAR)
    0x0127,                     # LATIN SMALL LETTER H WITH STROKE (LATIN SMALL LETTER H BAR)
    0x0128,                     # LATIN CAPITAL LETTER I WITH TILDE (LATIN CAPITAL LETTER I TILDE)
    0x0129,                     # LATIN SMALL LETTER I WITH TILDE (LATIN SMALL LETTER I TILDE)
    0x012a,                     # LATIN CAPITAL LETTER I WITH MACRON (LATIN CAPITAL LETTER I MACRON)
    0x012b,                     # LATIN SMALL LETTER I WITH MACRON (LATIN SMALL LETTER I MACRON)
    0x012c,                     # LATIN CAPITAL LETTER I WITH BREVE (LATIN CAPITAL LETTER I BREVE)
    0x012d,                     # LATIN SMALL LETTER I WITH BREVE (LATIN SMALL LETTER I BREVE)
    0x012e,                     # LATIN CAPITAL LETTER I WITH OGONEK (LATIN CAPITAL LETTER I OGONEK)
    0x012f,                     # LATIN SMALL LETTER I WITH OGONEK (LATIN SMALL LETTER I OGONEK)
    0x0130,                     # LATIN CAPITAL LETTER I WITH DOT ABOVE (LATIN CAPITAL LETTER I DOT)
    0x0131,                     # LATIN SMALL LETTER DOTLESS I
    0x0132,                     # LATIN CAPITAL LIGATURE IJ (LATIN CAPITAL LETTER I J)
    0x0133,                     # LATIN SMALL LIGATURE IJ (LATIN SMALL LETTER I J)
    0x0134,                     # LATIN CAPITAL LETTER J WITH CIRCUMFLEX (LATIN CAPITAL LETTER J CIRCUMFLEX)
    0x0135,                     # LATIN SMALL LETTER J WITH CIRCUMFLEX (LATIN SMALL LETTER J CIRCUMFLEX)
    0x0136,                     # LATIN CAPITAL LETTER K WITH CEDILLA (LATIN CAPITAL LETTER K CEDILLA)
    0x0137,                     # LATIN SMALL LETTER K WITH CEDILLA (LATIN SMALL LETTER K CEDILLA)
    0x0138,                     # LATIN SMALL LETTER KRA
    0x0139,                     # LATIN CAPITAL LETTER L WITH ACUTE (LATIN CAPITAL LETTER L ACUTE)
    0x013a,                     # LATIN SMALL LETTER L WITH ACUTE (LATIN SMALL LETTER L ACUTE)
    0x013b,                     # LATIN CAPITAL LETTER L WITH CEDILLA (LATIN CAPITAL LETTER L CEDILLA)
    0x013c,                     # LATIN SMALL LETTER L WITH CEDILLA (LATIN SMALL LETTER L CEDILLA)
    0x013d,                     # LATIN CAPITAL LETTER L WITH CARON (LATIN CAPITAL LETTER L HACEK)
    0x013e,                     # LATIN SMALL LETTER L WITH CARON (LATIN SMALL LETTER L HACEK)
    0x013f,                     # LATIN CAPITAL LETTER L WITH MIDDLE DOT
    0x0140,                     # LATIN SMALL LETTER L WITH MIDDLE DOT
    0x0141,                     # LATIN CAPITAL LETTER L WITH STROKE (LATIN CAPITAL LETTER L SLASH)
    0x0142,                     # LATIN SMALL LETTER L WITH STROKE (LATIN SMALL LETTER L SLASH)
    0x0143,                     # LATIN CAPITAL LETTER N WITH ACUTE (LATIN CAPITAL LETTER N ACUTE)
    0x0144,                     # LATIN SMALL LETTER N WITH ACUTE (LATIN SMALL LETTER N ACUTE)
    0x0145,                     # LATIN CAPITAL LETTER N WITH CEDILLA (LATIN CAPITAL LETTER N CEDILLA)
    0x0146,                     # LATIN SMALL LETTER N WITH CEDILLA (LATIN SMALL LETTER N CEDILLA)
    0x0147,                     # LATIN CAPITAL LETTER N WITH CARON (LATIN CAPITAL LETTER N HACEK)
    0x0148,                     # LATIN SMALL LETTER N WITH CARON (LATIN SMALL LETTER N HACEK)
    0x0149,                     # LATIN SMALL LETTER N PRECEDED BY APOSTROPHE (LATIN SMALL LETTER APOSTROPHE N)
    0x014a,                     # LATIN CAPITAL LETTER ENG
    0x014b,                     # LATIN SMALL LETTER ENG
    0x014c,                     # LATIN CAPITAL LETTER O WITH MACRON (LATIN CAPITAL LETTER O MACRON)
    0x014d,                     # LATIN SMALL LETTER O WITH MACRON (LATIN SMALL LETTER O MACRON)
    0x014e,                     # LATIN CAPITAL LETTER O WITH BREVE (LATIN CAPITAL LETTER O BREVE)
    0x014f,                     # LATIN SMALL LETTER O WITH BREVE (LATIN SMALL LETTER O BREVE)
    0x0150,                     # LATIN CAPITAL LETTER O WITH DOUBLE ACUTE (LATIN CAPITAL LETTER O DOUBLE ACUTE)
    0x0151,                     # LATIN SMALL LETTER O WITH DOUBLE ACUTE (LATIN SMALL LETTER O DOUBLE ACUTE)
    0x0152,                     # LATIN CAPITAL LIGATURE OE (LATIN CAPITAL LETTER O E)
    0x0153,                     # LATIN SMALL LIGATURE OE (LATIN SMALL LETTER O E)
    0x0154,                     # LATIN CAPITAL LETTER R WITH ACUTE (LATIN CAPITAL LETTER R ACUTE)
    0x0155,                     # LATIN SMALL LETTER R WITH ACUTE (LATIN SMALL LETTER R ACUTE)
    0x0156,                     # LATIN CAPITAL LETTER R WITH CEDILLA (LATIN CAPITAL LETTER R CEDILLA)
    0x0157,                     # LATIN SMALL LETTER R WITH CEDILLA (LATIN SMALL LETTER R CEDILLA)
    0x0158,                     # LATIN CAPITAL LETTER R WITH CARON (LATIN CAPITAL LETTER R HACEK)
    0x0159,                     # LATIN SMALL LETTER R WITH CARON (LATIN SMALL LETTER R HACEK)
    0x015a,                     # LATIN CAPITAL LETTER S WITH ACUTE (LATIN CAPITAL LETTER S ACUTE)
    0x015b,                     # LATIN SMALL LETTER S WITH ACUTE (LATIN SMALL LETTER S ACUTE)
    0x015c,                     # LATIN CAPITAL LETTER S WITH CIRCUMFLEX (LATIN CAPITAL LETTER S CIRCUMFLEX)
    0x015d,                     # LATIN SMALL LETTER S WITH CIRCUMFLEX (LATIN SMALL LETTER S CIRCUMFLEX)
    0x015e,                     # LATIN CAPITAL LETTER S WITH CEDILLA (LATIN CAPITAL LETTER S CEDILLA)
    0x015f,                     # LATIN SMALL LETTER S WITH CEDILLA (LATIN SMALL LETTER S CEDILLA)
    0x0160,                     # LATIN CAPITAL LETTER S WITH CARON (LATIN CAPITAL LETTER S HACEK)
    0x0161,                     # LATIN SMALL LETTER S WITH CARON (LATIN SMALL LETTER S HACEK)
    0x0162,                     # LATIN CAPITAL LETTER T WITH CEDILLA (LATIN CAPITAL LETTER T CEDILLA)
    0x0163,                     # LATIN SMALL LETTER T WITH CEDILLA (LATIN SMALL LETTER T CEDILLA)
    0x0164,                     # LATIN CAPITAL LETTER T WITH CARON (LATIN CAPITAL LETTER T HACEK)
    0x0165,                     # LATIN SMALL LETTER T WITH CARON (LATIN SMALL LETTER T HACEK)
    0x0166,                     # LATIN CAPITAL LETTER T WITH STROKE (LATIN CAPITAL LETTER T BAR)
    0x0167,                     # LATIN SMALL LETTER T WITH STROKE (LATIN SMALL LETTER T BAR)
    0x0168,                     # LATIN CAPITAL LETTER U WITH TILDE (LATIN CAPITAL LETTER U TILDE)
    0x0169,                     # LATIN SMALL LETTER U WITH TILDE (LATIN SMALL LETTER U TILDE)
    0x016a,                     # LATIN CAPITAL LETTER U WITH MACRON (LATIN CAPITAL LETTER U MACRON)
    0x016b,                     # LATIN SMALL LETTER U WITH MACRON (LATIN SMALL LETTER U MACRON)
    0x016c,                     # LATIN CAPITAL LETTER U WITH BREVE (LATIN CAPITAL LETTER U BREVE)
    0x016d,                     # LATIN SMALL LETTER U WITH BREVE (LATIN SMALL LETTER U BREVE)
    0x016e,                     # LATIN CAPITAL LETTER U WITH RING ABOVE (LATIN CAPITAL LETTER U RING)
    0x016f,                     # LATIN SMALL LETTER U WITH RING ABOVE (LATIN SMALL LETTER U RING)
    0x0170,                     # LATIN CAPITAL LETTER U WITH DOUBLE ACUTE (LATIN CAPITAL LETTER U DOUBLE ACUTE)
    0x0171,                     # LATIN SMALL LETTER U WITH DOUBLE ACUTE (LATIN SMALL LETTER U DOUBLE ACUTE)
    0x0172,                     # LATIN CAPITAL LETTER U WITH OGONEK (LATIN CAPITAL LETTER U OGONEK)
    0x0173,                     # LATIN SMALL LETTER U WITH OGONEK (LATIN SMALL LETTER U OGONEK)
    0x0174,                     # LATIN CAPITAL LETTER W WITH CIRCUMFLEX (LATIN CAPITAL LETTER W CIRCUMFLEX)
    0x0175,                     # LATIN SMALL LETTER W WITH CIRCUMFLEX (LATIN SMALL LETTER W CIRCUMFLEX)
    0x0176,                     # LATIN CAPITAL LETTER Y WITH CIRCUMFLEX (LATIN CAPITAL LETTER Y CIRCUMFLEX)
    0x0177,                     # LATIN SMALL LETTER Y WITH CIRCUMFLEX (LATIN SMALL LETTER Y CIRCUMFLEX)
    0x0178,                     # LATIN CAPITAL LETTER Y WITH DIAERESIS (LATIN CAPITAL LETTER Y DIAERESIS)
    0x0179,                     # LATIN CAPITAL LETTER Z WITH ACUTE (LATIN CAPITAL LETTER Z ACUTE)
    0x017a,                     # LATIN SMALL LETTER Z WITH ACUTE (LATIN SMALL LETTER Z ACUTE)
    0x017b,                     # LATIN CAPITAL LETTER Z WITH DOT ABOVE (LATIN CAPITAL LETTER Z DOT)
    0x017c,                     # LATIN SMALL LETTER Z WITH DOT ABOVE (LATIN SMALL LETTER Z DOT)
    0x017d,                     # LATIN CAPITAL LETTER Z WITH CARON (LATIN CAPITAL LETTER Z HACEK)
    0x017e,                     # LATIN SMALL LETTER Z WITH CARON (LATIN SMALL LETTER Z HACEK)
    0x017f,                     # LATIN SMALL LETTER LONG S
    0x0192,                     # LATIN SMALL LETTER F WITH HOOK (LATIN SMALL LETTER SCRIPT F)
    0x01fa,                     # LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE
    0x01fb,                     # LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE
    0x01fc,                     # LATIN CAPITAL LETTER AE WITH ACUTE
    0x01fd,                     # LATIN SMALL LETTER AE WITH ACUTE
    0x01fe,                     # LATIN CAPITAL LETTER O WITH STROKE AND ACUTE
    0x01ff,                     # LATIN SMALL LETTER O WITH STROKE AND ACUTE
    0x02c6,                     # MODIFIER LETTER CIRCUMFLEX ACCENT (MODIFIER LETTER CIRCUMFLEX)
    0x02c7,                     # CARON (MODIFIER LETTER HACEK)
    0x02c9,                     # MODIFIER LETTER MACRON
    0x02d8,                     # BREVE (SPACING BREVE)
    0x02d9,                     # DOT ABOVE (SPACING DOT ABOVE)
    0x02da,                     # RING ABOVE (SPACING RING ABOVE)
    0x02db,                     # OGONEK (SPACING OGONEK)
    0x02dc,                     # SMALL TILDE (SPACING TILDE)
    0x02dd,                     # DOUBLE ACUTE ACCENT (SPACING DOUBLE ACUTE)
    0x0384,                     # GREEK TONOS (GREEK SPACING TONOS)
    0x0385,                     # GREEK DIALYTIKA TONOS (GREEK SPACING DIAERESIS TONOS)
    0x0386,                     # GREEK CAPITAL LETTER ALPHA WITH TONOS (GREEK CAPITAL LETTER ALPHA TONOS)
    0x0387,                     # GREEK ANO TELEIA
    0x0388,                     # GREEK CAPITAL LETTER EPSILON WITH TONOS (GREEK CAPITAL LETTER EPSILON TONOS)
    0x0389,                     # GREEK CAPITAL LETTER ETA WITH TONOS (GREEK CAPITAL LETTER ETA TONOS)
    0x038a,                     # GREEK CAPITAL LETTER IOTA WITH TONOS (GREEK CAPITAL LETTER IOTA TONOS)
    0x038c,                     # GREEK CAPITAL LETTER OMICRON WITH TONOS (GREEK CAPITAL LETTER OMICRON TONOS)
    0x038e,                     # GREEK CAPITAL LETTER UPSILON WITH TONOS (GREEK CAPITAL LETTER UPSILON TONOS)
    0x038f,                     # GREEK CAPITAL LETTER OMEGA WITH TONOS (GREEK CAPITAL LETTER OMEGA TONOS)
    0x0390,                     # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS (GREEK SMALL LETTER IOTA DIAERESIS TONOS)
    0x0391,                     # GREEK CAPITAL LETTER ALPHA
    0x0392,                     # GREEK CAPITAL LETTER BETA
    0x0393,                     # GREEK CAPITAL LETTER GAMMA
    0x0394,                     # GREEK CAPITAL LETTER DELTA
    0x0395,                     # GREEK CAPITAL LETTER EPSILON
    0x0396,                     # GREEK CAPITAL LETTER ZETA
    0x0397,                     # GREEK CAPITAL LETTER ETA
    0x0398,                     # GREEK CAPITAL LETTER THETA
    0x0399,                     # GREEK CAPITAL LETTER IOTA
    0x039a,                     # GREEK CAPITAL LETTER KAPPA
    0x039b,                     # GREEK CAPITAL LETTER LAMDA (GREEK CAPITAL LETTER LAMBDA)
    0x039c,                     # GREEK CAPITAL LETTER MU
    0x039d,                     # GREEK CAPITAL LETTER NU
    0x039e,                     # GREEK CAPITAL LETTER XI
    0x039f,                     # GREEK CAPITAL LETTER OMICRON
    0x03a0,                     # GREEK CAPITAL LETTER PI
    0x03a1,                     # GREEK CAPITAL LETTER RHO
    0x03a3,                     # GREEK CAPITAL LETTER SIGMA
    0x03a4,                     # GREEK CAPITAL LETTER TAU
    0x03a5,                     # GREEK CAPITAL LETTER UPSILON
    0x03a6,                     # GREEK CAPITAL LETTER PHI
    0x03a7,                     # GREEK CAPITAL LETTER CHI
    0x03a8,                     # GREEK CAPITAL LETTER PSI
    0x03a9,                     # GREEK CAPITAL LETTER OMEGA
    0x03aa,                     # GREEK CAPITAL LETTER IOTA WITH DIALYTIKA (GREEK CAPITAL LETTER IOTA DIAERESIS)
    0x03ab,                     # GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA (GREEK CAPITAL LETTER UPSILON DIAERESIS)
    0x03ac,                     # GREEK SMALL LETTER ALPHA WITH TONOS (GREEK SMALL LETTER ALPHA TONOS)
    0x03ad,                     # GREEK SMALL LETTER EPSILON WITH TONOS (GREEK SMALL LETTER EPSILON TONOS)
    0x03ae,                     # GREEK SMALL LETTER ETA WITH TONOS (GREEK SMALL LETTER ETA TONOS)
    0x03af,                     # GREEK SMALL LETTER IOTA WITH TONOS (GREEK SMALL LETTER IOTA TONOS)
    0x03b0,                     # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS (GREEK SMALL LETTER UPSILON DIAERESIS TONOS)
    0x03b1,                     # GREEK SMALL LETTER ALPHA
    0x03b2,                     # GREEK SMALL LETTER BETA
    0x03b3,                     # GREEK SMALL LETTER GAMMA
    0x03b4,                     # GREEK SMALL LETTER DELTA
    0x03b5,                     # GREEK SMALL LETTER EPSILON
    0x03b6,                     # GREEK SMALL LETTER ZETA
    0x03b7,                     # GREEK SMALL LETTER ETA
    0x03b8,                     # GREEK SMALL LETTER THETA
    0x03b9,                     # GREEK SMALL LETTER IOTA
    0x03ba,                     # GREEK SMALL LETTER KAPPA
    0x03bb,                     # GREEK SMALL LETTER LAMDA (GREEK SMALL LETTER LAMBDA)
    0x03bc,                     # GREEK SMALL LETTER MU
    0x03bd,                     # GREEK SMALL LETTER NU
    0x03be,                     # GREEK SMALL LETTER XI
    0x03bf,                     # GREEK SMALL LETTER OMICRON
    0x03c0,                     # GREEK SMALL LETTER PI
    0x03c1,                     # GREEK SMALL LETTER RHO
    0x03c2,                     # GREEK SMALL LETTER FINAL SIGMA
    0x03c3,                     # GREEK SMALL LETTER SIGMA
    0x03c4,                     # GREEK SMALL LETTER TAU
    0x03c5,                     # GREEK SMALL LETTER UPSILON
    0x03c6,                     # GREEK SMALL LETTER PHI
    0x03c7,                     # GREEK SMALL LETTER CHI
    0x03c8,                     # GREEK SMALL LETTER PSI
    0x03c9,                     # GREEK SMALL LETTER OMEGA
    0x03ca,                     # GREEK SMALL LETTER IOTA WITH DIALYTIKA (GREEK SMALL LETTER IOTA DIAERESIS)
    0x03cb,                     # GREEK SMALL LETTER UPSILON WITH DIALYTIKA (GREEK SMALL LETTER UPSILON DIAERESIS)
    0x03cc,                     # GREEK SMALL LETTER OMICRON WITH TONOS (GREEK SMALL LETTER OMICRON TONOS)
    0x03cd,                     # GREEK SMALL LETTER UPSILON WITH TONOS (GREEK SMALL LETTER UPSILON TONOS)
    0x03ce,                     # GREEK SMALL LETTER OMEGA WITH TONOS (GREEK SMALL LETTER OMEGA TONOS)
    0x0400,                     # CYRILLIC CAPITAL LETTER IE WITH GRAVE
    0x0401,                     # CYRILLIC CAPITAL LETTER IO
    0x0402,                     # CYRILLIC CAPITAL LETTER DJE
    0x0403,                     # CYRILLIC CAPITAL LETTER GJE
    0x0404,                     # CYRILLIC CAPITAL LETTER UKRAINIAN IE (CYRILLIC CAPITAL LETTER E)
    0x0405,                     # CYRILLIC CAPITAL LETTER DZE
    0x0406,                     # CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I (CYRILLIC CAPITAL LETTER I)
    0x0407,                     # CYRILLIC CAPITAL LETTER YI
    0x0408,                     # CYRILLIC CAPITAL LETTER JE
    0x0409,                     # CYRILLIC CAPITAL LETTER LJE
    0x040a,                     # CYRILLIC CAPITAL LETTER NJE
    0x040b,                     # CYRILLIC CAPITAL LETTER TSHE
    0x040c,                     # CYRILLIC CAPITAL LETTER KJE
    0x040D,                     # CYRILLIC CAPITAL LETTER I WITH GRAVE
    0x040e,                     # CYRILLIC CAPITAL LETTER SHORT U
    0x040f,                     # CYRILLIC CAPITAL LETTER DZHE
    0x0410,                     # CYRILLIC CAPITAL LETTER A
    0x0411,                     # CYRILLIC CAPITAL LETTER BE
    0x0412,                     # CYRILLIC CAPITAL LETTER VE
    0x0413,                     # CYRILLIC CAPITAL LETTER GHE (CYRILLIC CAPITAL LETTER GE)
    0x0414,                     # CYRILLIC CAPITAL LETTER DE
    0x0415,                     # CYRILLIC CAPITAL LETTER IE
    0x0416,                     # CYRILLIC CAPITAL LETTER ZHE
    0x0417,                     # CYRILLIC CAPITAL LETTER ZE
    0x0418,                     # CYRILLIC CAPITAL LETTER I (CYRILLIC CAPITAL LETTER II)
    0x0419,                     # CYRILLIC CAPITAL LETTER SHORT I (CYRILLIC CAPITAL LETTER SHORT II)
    0x041a,                     # CYRILLIC CAPITAL LETTER KA
    0x041b,                     # CYRILLIC CAPITAL LETTER EL
    0x041c,                     # CYRILLIC CAPITAL LETTER EM
    0x041d,                     # CYRILLIC CAPITAL LETTER EN
    0x041e,                     # CYRILLIC CAPITAL LETTER O
    0x041f,                     # CYRILLIC CAPITAL LETTER PE
    0x0420,                     # CYRILLIC CAPITAL LETTER ER
    0x0421,                     # CYRILLIC CAPITAL LETTER ES
    0x0422,                     # CYRILLIC CAPITAL LETTER TE
    0x0423,                     # CYRILLIC CAPITAL LETTER U
    0x0424,                     # CYRILLIC CAPITAL LETTER EF
    0x0425,                     # CYRILLIC CAPITAL LETTER HA (CYRILLIC CAPITAL LETTER KHA)
    0x0426,                     # CYRILLIC CAPITAL LETTER TSE
    0x0427,                     # CYRILLIC CAPITAL LETTER CHE
    0x0428,                     # CYRILLIC CAPITAL LETTER SHA
    0x0429,                     # CYRILLIC CAPITAL LETTER SHCHA
    0x042a,                     # CYRILLIC CAPITAL LETTER HARD SIGN
    0x042b,                     # CYRILLIC CAPITAL LETTER YERU (CYRILLIC CAPITAL LETTER YERI)
    0x042c,                     # CYRILLIC CAPITAL LETTER SOFT SIGN
    0x042d,                     # CYRILLIC CAPITAL LETTER E (CYRILLIC CAPITAL LETTER REVERSED E)
    0x042e,                     # CYRILLIC CAPITAL LETTER YU (CYRILLIC CAPITAL LETTER IU)
    0x042f,                     # CYRILLIC CAPITAL LETTER YA (CYRILLIC CAPITAL LETTER IA)
    0x0430,                     # CYRILLIC SMALL LETTER A
    0x0431,                     # CYRILLIC SMALL LETTER BE
    0x0432,                     # CYRILLIC SMALL LETTER VE
    0x0433,                     # CYRILLIC SMALL LETTER GHE (CYRILLIC SMALL LETTER GE)
    0x0434,                     # CYRILLIC SMALL LETTER DE
    0x0435,                     # CYRILLIC SMALL LETTER IE
    0x0436,                     # CYRILLIC SMALL LETTER ZHE
    0x0437,                     # CYRILLIC SMALL LETTER ZE
    0x0438,                     # CYRILLIC SMALL LETTER I (CYRILLIC SMALL LETTER II)
    0x0439,                     # CYRILLIC SMALL LETTER SHORT I (CYRILLIC SMALL LETTER SHORT II)
    0x043a,                     # CYRILLIC SMALL LETTER KA
    0x043b,                     # CYRILLIC SMALL LETTER EL
    0x043c,                     # CYRILLIC SMALL LETTER EM
    0x043d,                     # CYRILLIC SMALL LETTER EN
    0x043e,                     # CYRILLIC SMALL LETTER O
    0x043f,                     # CYRILLIC SMALL LETTER PE
    0x0440,                     # CYRILLIC SMALL LETTER ER
    0x0441,                     # CYRILLIC SMALL LETTER ES
    0x0442,                     # CYRILLIC SMALL LETTER TE
    0x0443,                     # CYRILLIC SMALL LETTER U
    0x0444,                     # CYRILLIC SMALL LETTER EF
    0x0445,                     # CYRILLIC SMALL LETTER HA (CYRILLIC SMALL LETTER KHA)
    0x0446,                     # CYRILLIC SMALL LETTER TSE
    0x0447,                     # CYRILLIC SMALL LETTER CHE
    0x0448,                     # CYRILLIC SMALL LETTER SHA
    0x0449,                     # CYRILLIC SMALL LETTER SHCHA
    0x044a,                     # CYRILLIC SMALL LETTER HARD SIGN
    0x044b,                     # CYRILLIC SMALL LETTER YERU (CYRILLIC SMALL LETTER YERI)
    0x044c,                     # CYRILLIC SMALL LETTER SOFT SIGN
    0x044d,                     # CYRILLIC SMALL LETTER E (CYRILLIC SMALL LETTER REVERSED E)
    0x044e,                     # CYRILLIC SMALL LETTER YU (CYRILLIC SMALL LETTER IU)
    0x044f,                     # CYRILLIC SMALL LETTER YA (CYRILLIC SMALL LETTER IA)
    0x0450,                     # CYRILLIC SMALL LETTER IE WITH GRAVE
    0x0451,                     # CYRILLIC SMALL LETTER IO
    0x0452,                     # CYRILLIC SMALL LETTER DJE
    0x0453,                     # CYRILLIC SMALL LETTER GJE
    0x0454,                     # CYRILLIC SMALL LETTER UKRAINIAN IE (CYRILLIC SMALL LETTER E)
    0x0455,                     # CYRILLIC SMALL LETTER DZE
    0x0456,                     # CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I (CYRILLIC SMALL LETTER I)
    0x0457,                     # CYRILLIC SMALL LETTER YI
    0x0458,                     # CYRILLIC SMALL LETTER JE
    0x0459,                     # CYRILLIC SMALL LETTER LJE
    0x045a,                     # CYRILLIC SMALL LETTER NJE
    0x045b,                     # CYRILLIC SMALL LETTER TSHE
    0x045c,                     # CYRILLIC SMALL LETTER KJE
    0x045D,                     # CYRILLIC SMALL LETTER I WITH GRAVE
    0x045e,                     # CYRILLIC SMALL LETTER SHORT U
    0x045f,                     # CYRILLIC SMALL LETTER DZHE
    0x0490,                     # CYRILLIC CAPITAL LETTER GHE WITH UPTURN (CYRILLIC CAPITAL LETTER GE WITH UPTURN)
    0x0491,                     # CYRILLIC SMALL LETTER GHE WITH UPTURN (CYRILLIC SMALL LETTER GE WITH UPTURN)
    0x1e80,                     # LATIN CAPITAL LETTER W WITH GRAVE
    0x1e81,                     # LATIN SMALL LETTER W WITH GRAVE
    0x1e82,                     # LATIN CAPITAL LETTER W WITH ACUTE
    0x1e83,                     # LATIN SMALL LETTER W WITH ACUTE
    0x1e84,                     # LATIN CAPITAL LETTER W WITH DIAERESIS
    0x1e85,                     # LATIN SMALL LETTER W WITH DIAERESIS
    0x1ef2,                     # LATIN CAPITAL LETTER Y WITH GRAVE
    0x1ef3,                     # LATIN SMALL LETTER Y WITH GRAVE
    0x2013,                     # EN DASH
    0x2014,                     # EM DASH
    0x2015,                     # HORIZONTAL BAR (QUOTATION DASH)
    0x2017,                     # DOUBLE LOW LINE (SPACING DOUBLE UNDERSCORE)
    0x2018,                     # LEFT SINGLE QUOTATION MARK (SINGLE TURNED COMMA QUOTATION MARK)
    0x2019,                     # RIGHT SINGLE QUOTATION MARK (SINGLE COMMA QUOTATION MARK)
    0x201a,                     # SINGLE LOW-9 QUOTATION MARK (LOW SINGLE COMMA QUOTATION MARK)
    0x201b,                     # SINGLE HIGH-REVERSED-9 QUOTATION MARK (SINGLE REVERSED COMMA QUOTATION MARK)
    0x201c,                     # LEFT DOUBLE QUOTATION MARK (DOUBLE TURNED COMMA QUOTATION MARK)
    0x201d,                     # RIGHT DOUBLE QUOTATION MARK (DOUBLE COMMA QUOTATION MARK)
    0x201e,                     # DOUBLE LOW-9 QUOTATION MARK (LOW DOUBLE COMMA QUOTATION MARK)
    0x2020,                     # DAGGER
    0x2021,                     # DOUBLE DAGGER
    0x2022,                     # BULLET
    0x2026,                     # HORIZONTAL ELLIPSIS
    0x2030,                     # PER MILLE SIGN
    0x2032,                     # PRIME
    0x2033,                     # DOUBLE PRIME
    0x2039,                     # SINGLE LEFT-POINTING ANGLE QUOTATION MARK (LEFT POINTING SINGLE GUILLEMET)
    0x203a,                     # SINGLE RIGHT-POINTING ANGLE QUOTATION MARK (RIGHT POINTING SINGLE GUILLEMET)
    0x203c,                     # DOUBLE EXCLAMATION MARK
    0x203e,                     # OVERLINE (SPACING OVERSCORE)
    0x2044,                     # FRACTION SLASH
    0x207f,                     # SUPERSCRIPT LATIN SMALL LETTER N
    0x20a3,                     # FRENCH FRANC SIGN
    0x20a4,                     # LIRA SIGN
    0x20a7,                     # PESETA SIGN
    0x20ac,                     # EURO SIGN
    0x2105,                     # CARE OF
    0x2113,                     # SCRIPT SMALL L
    0x2116,                     # NUMERO SIGN (NUMERO)
    0x2122,                     # TRADE MARK SIGN (TRADEMARK)
    0x2126,                     # OHM SIGN (OHM)
    0x212e,                     # ESTIMATED SYMBOL
    0x215b,                     # VULGAR FRACTION ONE EIGHTH (FRACTION ONE EIGHTH)
    0x215c,                     # VULGAR FRACTION THREE EIGHTHS (FRACTION THREE EIGHTHS)
    0x215d,                     # VULGAR FRACTION FIVE EIGHTHS (FRACTION FIVE EIGHTHS)
    0x215e,                     # VULGAR FRACTION SEVEN EIGHTHS (FRACTION SEVEN EIGHTHS)
    0x2190,                     # LEFTWARDS ARROW (LEFT ARROW)
    0x2191,                     # UPWARDS ARROW (UP ARROW)
    0x2192,                     # RIGHTWARDS ARROW (RIGHT ARROW)
    0x2193,                     # DOWNWARDS ARROW (DOWN ARROW)
    0x2194,                     # LEFT RIGHT ARROW
    0x2195,                     # UP DOWN ARROW
    0x21a8,                     # UP DOWN ARROW WITH BASE
    0x2202,                     # PARTIAL DIFFERENTIAL
    0x2206,                     # INCREMENT
    0x220f,                     # N-ARY PRODUCT
    0x2211,                     # N-ARY SUMMATION
    0x2212,                     # MINUS SIGN
    0x2215,                     # DIVISION SLASH
    0x2219,                     # BULLET OPERATOR
    0x221a,                     # SQUARE ROOT
    0x221e,                     # INFINITY
    0x221f,                     # RIGHT ANGLE
    0x2229,                     # INTERSECTION
    0x222b,                     # INTEGRAL
    0x2248,                     # ALMOST EQUAL TO
    0x2260,                     # NOT EQUAL TO
    0x2261,                     # IDENTICAL TO
    0x2264,                     # LESS-THAN OR EQUAL TO (LESS THAN OR EQUAL TO)
    0x2265,                     # GREATER-THAN OR EQUAL TO (GREATER THAN OR EQUAL TO)
    0x2302,                     # HOUSE
    0x2310,                     # REVERSED NOT SIGN
    0x2320,                     # TOP HALF INTEGRAL
    0x2321,                     # BOTTOM HALF INTEGRAL
    0x2500,                     # BOX DRAWINGS LIGHT HORIZONTAL (FORMS LIGHT HORIZONTAL)
    0x2502,                     # BOX DRAWINGS LIGHT VERTICAL (FORMS LIGHT VERTICAL)
    0x250c,                     # BOX DRAWINGS LIGHT DOWN AND RIGHT (FORMS LIGHT DOWN AND RIGHT)
    0x2510,                     # BOX DRAWINGS LIGHT DOWN AND LEFT (FORMS LIGHT DOWN AND LEFT)
    0x2514,                     # BOX DRAWINGS LIGHT UP AND RIGHT (FORMS LIGHT UP AND RIGHT)
    0x2518,                     # BOX DRAWINGS LIGHT UP AND LEFT (FORMS LIGHT UP AND LEFT)
    0x251c,                     # BOX DRAWINGS LIGHT VERTICAL AND RIGHT (FORMS LIGHT VERTICAL AND RIGHT)
    0x2524,                     # BOX DRAWINGS LIGHT VERTICAL AND LEFT (FORMS LIGHT VERTICAL AND LEFT)
    0x252c,                     # BOX DRAWINGS LIGHT DOWN AND HORIZONTAL (FORMS LIGHT DOWN AND HORIZONTAL)
    0x2534,                     # BOX DRAWINGS LIGHT UP AND HORIZONTAL (FORMS LIGHT UP AND HORIZONTAL)
    0x253c,                     # BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL (FORMS LIGHT VERTICAL AND HORIZONTAL)
    0x2550,                     # BOX DRAWINGS DOUBLE HORIZONTAL (FORMS DOUBLE HORIZONTAL)
    0x2551,                     # BOX DRAWINGS DOUBLE VERTICAL (FORMS DOUBLE VERTICAL)
    0x2552,                     # BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE (FORMS DOWN SINGLE AND RIGHT DOUBLE)
    0x2553,                     # BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE (FORMS DOWN DOUBLE AND RIGHT SINGLE)
    0x2554,                     # BOX DRAWINGS DOUBLE DOWN AND RIGHT (FORMS DOUBLE DOWN AND RIGHT)
    0x2555,                     # BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE (FORMS DOWN SINGLE AND LEFT DOUBLE)
    0x2556,                     # BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE (FORMS DOWN DOUBLE AND LEFT SINGLE)
    0x2557,                     # BOX DRAWINGS DOUBLE DOWN AND LEFT (FORMS DOUBLE DOWN AND LEFT)
    0x2558,                     # BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE (FORMS UP SINGLE AND RIGHT DOUBLE)
    0x2559,                     # BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE (FORMS UP DOUBLE AND RIGHT SINGLE)
    0x255a,                     # BOX DRAWINGS DOUBLE UP AND RIGHT (FORMS DOUBLE UP AND RIGHT)
    0x255b,                     # BOX DRAWINGS UP SINGLE AND LEFT DOUBLE (FORMS UP SINGLE AND LEFT DOUBLE)
    0x255c,                     # BOX DRAWINGS UP DOUBLE AND LEFT SINGLE (FORMS UP DOUBLE AND LEFT SINGLE)
    0x255d,                     # BOX DRAWINGS DOUBLE UP AND LEFT (FORMS DOUBLE UP AND LEFT)
    0x255e,                     # BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE (FORMS VERTICAL SINGLE AND RIGHT DOUBLE)
    0x255f,                     # BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE (FORMS VERTICAL DOUBLE AND RIGHT SINGLE)
    0x2560,                     # BOX DRAWINGS DOUBLE VERTICAL AND RIGHT (FORMS DOUBLE VERTICAL AND RIGHT)
    0x2561,                     # BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE (FORMS VERTICAL SINGLE AND LEFT DOUBLE)
    0x2562,                     # BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE (FORMS VERTICAL DOUBLE AND LEFT SINGLE)
    0x2563,                     # BOX DRAWINGS DOUBLE VERTICAL AND LEFT (FORMS DOUBLE VERTICAL AND LEFT)
    0x2564,                     # BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE (FORMS DOWN SINGLE AND HORIZONTAL DOUBLE)
    0x2565,                     # BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE (FORMS DOWN DOUBLE AND HORIZONTAL SINGLE)
    0x2566,                     # BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL (FORMS DOUBLE DOWN AND HORIZONTAL)
    0x2567,                     # BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE (FORMS UP SINGLE AND HORIZONTAL DOUBLE)
    0x2568,                     # BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE (FORMS UP DOUBLE AND HORIZONTAL SINGLE)
    0x2569,                     # BOX DRAWINGS DOUBLE UP AND HORIZONTAL (FORMS DOUBLE UP AND HORIZONTAL)
    0x256a,                     # BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE (FORMS VERTICAL SINGLE AND HORIZONTAL DOUBLE)
    0x256b,                     # BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE (FORMS VERTICAL DOUBLE AND HORIZONTAL SINGLE)
    0x256c,                     # BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL (FORMS DOUBLE VERTICAL AND HORIZONTAL)
    0x2580,                     # UPPER HALF BLOCK
    0x2584,                     # LOWER HALF BLOCK
    0x2588,                     # FULL BLOCK
    0x258c,                     # LEFT HALF BLOCK
    0x2590,                     # RIGHT HALF BLOCK
    0x2591,                     # LIGHT SHADE
    0x2592,                     # MEDIUM SHADE
    0x2593,                     # DARK SHADE
    0x25a0,                     # BLACK SQUARE
    0x25a1,                     # WHITE SQUARE
    0x25aa,                     # BLACK SMALL SQUARE
    0x25ab,                     # WHITE SMALL SQUARE
    0x25ac,                     # BLACK RECTANGLE
    0x25b2,                     # BLACK UP-POINTING TRIANGLE (BLACK UP POINTING TRIANGLE)
    0x25ba,                     # BLACK RIGHT-POINTING POINTER (BLACK RIGHT POINTING POINTER)
    0x25bc,                     # BLACK DOWN-POINTING TRIANGLE (BLACK DOWN POINTING TRIANGLE)
    0x25c4,                     # BLACK LEFT-POINTING POINTER (BLACK LEFT POINTING POINTER)
    0x25ca,                     # LOZENGE
    0x25cb,                     # WHITE CIRCLE
    0x25cf,                     # BLACK CIRCLE
    0x25d8,                     # INVERSE BULLET
    0x25d9,                     # INVERSE WHITE CIRCLE
    0x25e6,                     # WHITE BULLET
    0x263a,                     # WHITE SMILING FACE
    0x263b,                     # BLACK SMILING FACE
    0x263c,                     # WHITE SUN WITH RAYS
    0x2640,                     # FEMALE SIGN
    0x2642,                     # MALE SIGN
    0x2660,                     # BLACK SPADE SUIT
    0x2663,                     # BLACK CLUB SUIT
    0x2665,                     # BLACK HEART SUIT
    0x2666,                     # BLACK DIAMOND SUIT
    0x266a,                     # EIGHTH NOTE
    0x266b,                     # BEAMED EIGHTH NOTES (BARRED EIGHTH NOTES)
    0xf001,                     # private use duplicate of U+FB01 LATIN SMALL LIGATURE FI
    0xf002,                     # private use duplicate of U+FB02 LATIN SMALL LIGATURE FL
    0xfb01,                     # LATIN SMALL LIGATURE FI
    0xfb02                      # LATIN SMALL LIGATURE FL
]
